Cart Redux Logic
uark-acm/bho-frontend pull request #10
Opened 2023-03-20 08:13 UTC by a-mufasa

Added the logic for the 4 actions: add item, remove item, increase quantity, decrease quantity. Currently we don't have anything related to incrementing/decrementing quantity of the cart items in our UI so that code is "unimplemented". The adding/removing of items though is called in the view inventory screen and view item modal.

2023-03-20 23:51 UTC, JackTNorris commented on dist/index.html
> +    <title>Boss Hog Outfitters</title>
Thank you for this

2023-03-21 00:09 UTC, JackTNorris requested changes

2023-03-21 00:09 UTC, JackTNorris commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.ADD_TO_CART: {
_nit_: I was initially thinking that we'd request all the clothing items from the backend once a user lands on the site and then we'd only be passing the "id" of an item into the cart as opposed to a whole object. I doubt the performance overhead of passing the whole object vs just the id is that great, so I'm fine with keeping this as is though. What are your thoughts? A big con to the approach I propose is the added minor complexity of using two arrays to tell exactly what is in your cart as opposed to one

2023-03-21 00:11 UTC, a-mufasa commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.DECREMENT_QUANTITY: {
I can delete them just fine since I havent implemented it anywhere. It would mean dropping that quantity value in this reducer file as well but that is no biggie. My initial reasoning was to match the implementation of the redux toolkit cart you linked in the Trello card but these do seem like extra 🤷.

2023-03-21 00:16 UTC, a-mufasa commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.ADD_TO_CART: {
I just wrote what was simpler. With that approach of pre-loading all the data onto the frontend, we may be able to only have the ID in the cart and match it up to the full array of items whenever we want to use those item values. I think for now (since we dont have any of that backend stuff set up), we can stick with this (or possibly permanently) since it makes it easier to work on the actual cart view when we decide to do that.

2023-03-21 00:25 UTC, a-mufasa commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.DECREMENT_QUANTITY: {
<img width="473" alt="image" src="https://user-images.githubusercontent.com/90020418/226493218-1951aba4-1211-4b1f-b674-0af8b3be8fa2.png">

Updated and it works still.

2023-03-21 04:08 UTC, JackTNorris commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.ADD_TO_CART: {
Sounds good to me

2023-03-21 04:08 UTC, JackTNorris commented on src/redux/reducers/Cart.reducer.ts
> +        case Action.DECREMENT_QUANTITY: {
Awesome, thank you

2023-03-21 04:09 UTC, JackTNorris approved these changes

2023-03-21 04:09 UTC, merged