Qr scanner
uark-acm/bho-frontend pull request #20
Opened 2023-04-20 19:28 UTC by dmroberts302

I Added QR code scanner functionality in route /checkInOut. Is it fine the QR code scanner does not load immediately, it takes like 1s to render?

2023-04-21 21:28 UTC, JackTNorris commented
Taking a second to render is perfectly fine

2023-04-21 22:30 UTC, JackTNorris requested changes

2023-04-21 22:30 UTC, JackTNorris commented on src/screens/CheckInOutScreen.tsx
> +const camStyle = {
Can we move this to a CSS file?

2023-04-21 22:30 UTC, JackTNorris commented on src/screens/CheckInOutScreen.tsx
> +const Custom = styled.button`
Go with an approach using the MUI buttons like done [here](https://github.com/uark-acm/bho-frontend/blob/a0e43077d1c46360685a1a9e8ef27abdb82c972f/src/components/ViewItemModal.tsx#L79-L87):

2023-04-23 07:07 UTC, dmroberts302 commented on src/screens/CheckInOutScreen.tsx
> +const camStyle = {
When looking back at the codeI noticed cam style had some redundant css which i removed.

2023-04-23 07:08 UTC, dmroberts302 commented on src/screens/CheckInOutScreen.tsx
> +const Custom = styled.button`
I have added the MUI Button to my code and it works perfectly fine!

2023-04-25 01:56 UTC, JackTNorris approved these changes

2023-04-25 01:56 UTC, JackTNorris commented on src/screens/CheckInOutScreen.tsx
> +                    style={{
_nit_: maybe move this to a css file if possible. Atm, I'll approve, but see if you can move it to a CSS file before merging

2023-04-26 06:13 UTC, dmroberts302 commented on src/screens/CheckInOutScreen.tsx
> +                    style={{
Hey Jack for some reason its not letting me add external css to a Material UI button.

2023-04-26 06:13 UTC, merged